### ISSUE TITLE
shows error

### ISSUE THREAD

**Issue by shravyavorugallu** [Mysterious-Owl/moodle#1]
it shows error while marking specific subjects automatically saying user 1     '% 'must be followed by '%' or '(', found: '%'

**Comment by Mysterious-Owl** [comment]
Can you send me the log file (it can be found in Mysterious Owl -> moodleprogram -> log -> all.log)? <br>
So I can help you with the issue

**Comment by Mysterious-Owl** [comment]
> it shows error while marking specific subjects automatically saying user 1 '% 'must be followed by '%' or '(', found: '%'

Can you send me the log file (it can be found in Mysterious Owl -> moodleprogram -> log -> all.log)?

So I can help you with the issue

**Comment by shravyavorugallu** [comment]
It shows empty file now earlier it shown the url opened and its ip address

**Comment by Mysterious-Owl** [comment]
Are you using code directly or the release?

**Comment by shravyavorugallu** [comment]
release

**Comment by Mysterious-Owl** [comment]
So did you tried using the browser while marking attendance?
If yes, try unchecking this option in settings and try again.
If not, try checking this option in settings and try again.
See if the error is for both or specific.
Its not showing any error in my case, though, are you using it for same college or different?

**Comment by shravyavorugallu** [comment]
yes I used used that browser option. Different college...i changed the link for a subject and its name and then used it

**Comment by shravyavorugallu** [comment]
[
[all.log](https://github.com/Mysterious-Owl/moodle/files/6574715/all.log)
](url)
   this is the all log file.......i unchecked that option but still it is showing the same error...
in the user file when i left the username password empty it said wrong credentials but when i entered the credentials it is showing that user1 error

**Comment by Mysterious-Owl** [comment]
I entered the same url, it shows Wrong Credentials to me, with my username and password there, try checking the config files once

**Comment by shravyavorugallu** [comment]
Ok

**Comment by Mysterious-Owl** [comment]
Now try using the updated version, it may show the type of error, which is causing this.
I just updated it, you can keep the old configuration files, by selecting the option during install, so it won't overwrite the timetable and user file

**Comment by shravyavorugallu** [comment]
ok i will do it

**Comment by Mysterious-Owl** [comment]
Since there is no response from your side, I am closing this issue.
