### ISSUE TITLE
QUERY

### ISSUE THREAD

**Issue by Dhruv082** [Mysterious-Owl/moodle#2]
CAN THIS APP BE USED TO MARK ATTENDANCE ON OTHER URLS OF MOODLE. AS I HAVE BEEN TRYING TO DO SO BUT COULDNT DO THAT.
PLEASE GUIDE IF POSSIBLE

**Comment by Mysterious-Owl** [comment]
I supposed that all the Moodle works same, but maybe my college did many changes to Moodle.
If you cooperate I will make one for your college too as only some elements needs to be renamed only, I suppose.
If you are willing please provide -
- URL
- username
- password

**Comment by Dhruv082** [comment]
URL: http://45.116.207.215/moodle/login/index.php
USERNAME: 20021869
PASSWORD:Rituraman@1

THANKS FOR YOUR SUPPORT MAN!!!
 I ALSO TRIED CHANGIING THE LINKS BUT GOT STUCK AT THE LOGIN LINK AS IT KEPT ON SEARCHING WITH YOUR UNIVERSITYS URL. ALTHOUGH I CHANGED THE LINKS OF SUBJECTS ATTENNDANCE RESPECTIVELY.

**Comment by Mysterious-Owl** [comment]
I am working on it

**Comment by Mysterious-Owl** [comment]
Can you Python code?

**Comment by Dhruv082** [comment]
No i cant
Just a rookie in coding

**Comment by Mysterious-Owl** [comment]
Ok, so your next attendance is at 3-5 right?

**Comment by Dhruv082** [comment]
my next attendance is from 3:05 to 4:05 of professional advance communication

**Comment by Mysterious-Owl** [comment]
Can you please mark it at 4pm, incase I forget to mark it. Actually I need
to test the test and my college session still not started. So I will mark
your attendance to test.

Thanks
Tanishq

**Comment by Dhruv082** [comment]
sure I will do that

**Comment by Mysterious-Owl** [comment]
I didn't perform the test today, although I did the necessary changes. So I will let you know tomorrow, after 3pm

**Comment by Dhruv082** [comment]
OKkkk

**Comment by Dhruv082** [comment]
Any progress brother!

**Comment by Mysterious-Owl** [comment]
Sorry, I was very busy today.
I actually made the necessary changes in code, I just need to test it, then I will convert into the software. 
I will make sure to do it tomorrow, do you any attendance to mark tomorrow?

**Comment by Mysterious-Owl** [comment]
> I ALSO TRIED CHANGIING THE LINKS BUT GOT STUCK AT THE LOGIN LINK AS IT KEPT ON SEARCHING WITH YOUR UNIVERSITYS URL. ALTHOUGH I CHANGED THE LINKS OF SUBJECTS ATTENNDANCE RESPECTIVELY.

Were you just trying to open Moodle here, or which option you clicked?

**Comment by Dhruv082** [comment]
> > I ALSO TRIED CHANGIING THE LINKS BUT GOT STUCK AT THE LOGIN LINK AS IT KEPT ON SEARCHING WITH YOUR UNIVERSITYS URL. ALTHOUGH I CHANGED THE LINKS OF SUBJECTS ATTENNDANCE RESPECTIVELY.
> 
> Were you just trying to open Moodle here, or which option you clicked?

I wasn't able to change the url of login moodle of my university

**Comment by Dhruv082** [comment]
Yes i do have attendance tomorrow

**Comment by Mysterious-Owl** [comment]
> > > I ALSO TRIED CHANGIING THE LINKS BUT GOT STUCK AT THE LOGIN LINK AS IT KEPT ON SEARCHING WITH YOUR UNIVERSITYS URL. ALTHOUGH I CHANGED THE LINKS OF SUBJECTS ATTENNDANCE RESPECTIVELY.
> > 
> > 
> > Were you just trying to open Moodle here, or which option you clicked?
> 
> I wasn't able to change the url of login moodle of my university

![image](https://user-images.githubusercontent.com/66870959/125109020-6f63e780-e100-11eb-8f46-5f5991fe66b7.png)

Were you clicking here?

**Comment by Dhruv082** [comment]
Well i thought that changing the url of ur University in the code might make it work
So, i changed the code a bit, then tried but it didn't work

**Comment by Mysterious-Owl** [comment]
Actually I mistakenly hard coded URL of my uni, but it did not affect the attendance part in GUI part, thats why I am asking.
Attendance unit should work fine!

**Comment by Dhruv082** [comment]
> Actually I mistakenly hard coded URL of my uni, but it did not affect the attendance part in GUI part, thats why I am asking.
> Attendance unit should work fine!

Okk So thats why i wast able to reach at my uni login page although Attendance unit was working fine i think

**Comment by Mysterious-Owl** [comment]
Great, so I changed that, most probably problem will be solved.
So were you able to change the time table?
(manually, no option in software currently)

**Comment by Dhruv082** [comment]
Yes I was able to change the time table and the list of subjects manually by altering in the excel file and the code as well.

**Comment by Mysterious-Owl** [comment]
Great!!

**Comment by Mysterious-Owl** [comment]
I uploaded the new release, just use the same installer and install it again in the same directory. 
> Don't forget to check the option to keep old cofig files

Any doubt or error, feel free to open another issue.

**Comment by Dhruv082** [comment]
Bro i installed the app but it is still opening your university's url.
Please guide.

**Comment by Mysterious-Owl** [comment]
So,

1. Did you installed the new version and opening the new version or by mistake chose the wrong directory?
2. Did you changed all the links or just some?

**Comment by Dhruv082** [comment]
What i did is delete all the older files

**Comment by Dhruv082** [comment]
And i installed it again. From the start

**Comment by Mysterious-Owl** [comment]
What about the links?
Did you tried changing the links?
> Its working fine in my pc

**Comment by Dhruv082** [comment]
i can only change the links of attendance one 
but firstly login url have to be changed too so that it accepts my credentials.

**Comment by Mysterious-Owl** [comment]
No!

**Comment by Mysterious-Owl** [comment]
Working process - 
When we open any attendance URL without loginin, it redirects to login page and then opens the attendance page and then its going to main page

**Comment by Dhruv082** [comment]
Do you use ig 
i could coummunicate with you there better

**Comment by Mysterious-Owl** [comment]
Actually not, I dont use social media.

**Comment by Mysterious-Owl** [comment]
```
[login0]
user = 20021869
pass = Rituraman@1

[links]
ds = http://45.116.207.215/moodle/mod/attendance/view.php?id=6203
optical = http://moodle.mitsgwalior.in/mod/attendance/view.php?id=49314
microprocessor lab = http://moodle.mitsgwalior.in/mod/attendance/view.php?id=48591
dm = http://moodle.mitsgwalior.in/mod/attendance/view.php?id=7142
dsp = http://moodle.mitsgwalior.in/mod/attendance/view.php?id=48692
minor project lab = http://moodle.mitsgwalior.in/mod/attendance/view.php?id=49726
mandi = http://moodle.mitsgwalior.in/mod/attendance/view.php?id=48916
```

Paste this in moodleprogram/config/user.ini and try once

**Comment by Dhruv082** [comment]
I WES ALTERING THIS ONLY AND IT WORKED 
I THOUGHT THAT THE WORKING PROCESS IS 
LOGIN
ATTENDANCE THEN MAIN PAGE


THANKS BUDDY

**Comment by Mysterious-Owl** [comment]
You can also use 
- task scheduler to automate all this 
- In settings uncheck the option, then browser will not open again and again

*WELCOME*
