### ISSUE TITLE
'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by rzyware** [Mysterious-Owl/moodle#4]
![Screenshot 2022-01-14 130441](https://user-images.githubusercontent.com/40365846/149501814-1256708a-4719-44e7-b65e-1a7542a8b855.jpg)

It happen too if i try to mark automatically in GUI with 'show browser while marking attendance?' unchecked.

**Comment by Mysterious-Owl** [comment]
Hi Rizki,
I guess this is happening because your website moodle version is different/customized/updated. I will be glad to help if you can share the website with me.

**Comment by rzyware** [comment]
Can I email you the website and my login?

**Comment by Mysterious-Owl** [comment]
Sure mysteriousowl9@gmail.com

**Comment by rzyware** [comment]
Thankyou. I already sent the website

**Comment by Mysterious-Owl** [comment]
Got it. Will try to make it compatible

**Comment by rzyware** [comment]
Thankyou!

**Comment by Mysterious-Owl** [comment]
Its working fine currently, for further testing I will test it tomorrow when attendance marking is open for any subject, can you please tell me time when its open for self recording and not mark it on your own?
Also tell me your time zone, I'm in IST

**Comment by rzyware** [comment]
Next attendance will open on 17 January, 07:30 AM - 08:30 AM. I'm in WIB

**Comment by Mysterious-Owl** [comment]
is there any in evening?
You are 1.5 hrs ahead of me

**Comment by rzyware** [comment]
There is. On 18th January, 1:30 PM - 2:00 PM

**Comment by Mysterious-Owl** [comment]
ok, why don't you just me the html code?
Next time when you mark attendance, try to save the HTML code of the attendance webpage(where 'Submit Attendance' is there) and next page(where we click on 'Present') and send it to me. HTML can se saved using CRTL+S.
I can work on that

**Comment by rzyware** [comment]
okkk. I will send the html code later when the attendance come out

**Comment by rzyware** [comment]
this is the code

[attendance view.txt](https://github.com/Mysterious-Owl/moodle/files/7878308/attendance.view.txt)
[attendance.txt](https://github.com/Mysterious-Owl/moodle/files/7878306/attendance.txt)

**Comment by Mysterious-Owl** [comment]
Are you using code or release?
Just to confirm "Hadir" means Present right?

**Comment by rzyware** [comment]
i use code.

yep. hadir means present.

**Comment by Mysterious-Owl** [comment]
So you can see the updated one and try it. Don't forget to tell me if it worked!
There is a minor change, by which it finds the Present option in website, for which CSS class is changed for your website. So I had put the "or" condition there.

**Comment by rzyware** [comment]
works perfectly

thankyou!!

**Comment by Mysterious-Owl** [comment]
Happy to help!!
